[build]
	publish = "_site"
	command = "npm run build"

[Settings]
  ID = "5d3e30a9-ff13-419a-9b09-5a2e08da5b7d"
  
[functions]
  directory = "netlify/functions"
  
[[redirects]]
  from = "/patreons-new-logo-design-is-good-actually"
  to = "/freelance/patreon-s-new-logo-design-is-good-actually/"
  status = 301
  
[[redirects]]
  from = "/notebook"
  to = "/p/notebook/"
  status = 301

[[redirects]]
  from = "/freelance"
  to = "/p/freelance/"
  status = 301
  
[[redirects]]
  from = "/stories"
  to = "/p/stories/"
  status = 301