[build]
	publish = "_site"
	command = "npm run build"

[Settings]
  ID = "5d3e30a9-ff13-419a-9b09-5a2e08da5b7d"
  
[functions]
  directory = "netlify/functions"
  
[[redirects]]
  from = "/patreons-new-logo-design-is-good-actually"
  to = "/freelance/patreon-s-new-logo-design-is-good-actually/"
  status = 301
  
[[redirects]]
  from = "/notebook"
  to = "/p/notebook/"
  status = 301

[[redirects]]
  from = "/freelance"
  to = "/p/freelance/"
  status = 301
  
[[redirects]]
  from = "/stories"
  to = "/p/stories/"
  status = 301
  
[[redirects]]
  from = "/notebook/*"
  to = "https://fromjason.xyz/p/notebook/:splat"
  status = 301
  
[[redirects]]
  from = "/freelance/*"
  to = "https://fromjason.xyz/p/freelance/:splat"
  status = 301
  
[[redirects]]
  from = "/stories/*"
  to = "https://fromjason.xyz/p/stories/:splat"
  status = 301

[[redirects]]
  from = "/stories/*"
  to = "https://fromjason.xyz/p/stories/:splat"
  status = 301
  
[[redirects]]
  from = "/yuck-leopard/"
  to = "/p/stories/s/oddities/yuck-leopard/"
  status = 301

[[redirects]]
  from = "/drunk-baby/"
  to = "/p/stories/s/oddities/drunk-baby/"
  status = 301
  
[[redirects]]
  from = "/irate-ivan/"
  to = "/p/stories/s/oddities/irate-ivan/"
  status = 301

[[redirects]]
  from = "/photog-phil/"
  to = "/p/stories/s/oddities/photog-phil/"
  status = 301
  
[[redirects]]
  from = "/shame-fish/"
  to = "/p/stories/s/oddities/shame-fish/"
  status = 301
  
[[redirects]]
  from = "/that-look-lion/"
  to = "/p/stories/s/oddities/that-look-lion/"
  status = 301